config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#show"
  resource :home, only: :show
  resources :users, only: [:index, :show, :edit, :update, :new, :create] do
    resources :registrations, only: [:new, :create]
  end  
end

app/models/allergy.rb
class Allergy < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '有り' },
    { id: 3, name: '無し' }
]
  end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood_type.rb
class BloodType < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'A型' },
    { id: 3, name: 'B型' },
    { id: 4, name: 'O型' },
    { id: 5, name: 'AB型' }
]
end

app/models/chronic_condition.rb
class ChronicCondition < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '有り' },
    { id: 3, name: '無し' }
]
 
  end
 

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user



end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  has_one :registration

  with_options presence: true do
    validates :address, :datetime, :public_uid
    validates :name, format: {with: /\A[ぁ-んァ-ン一-龥]/}
    validates :name_reading, format: {with: /\A[ァ-ヶー－]+\z/}
    validates :phone_number,format: {with: /\A\d{10,11}\z/}
    validates :body_weight, :height, format: {with: /\A[0-9]+\z/}
    validates :body_temperature, format: {with: /\A\d{1,2}(\.\d)?\z/}
    validates :blood_type_id, :allergy_id, :chronic_condition_id, :venue_id, numericality: { other_than: 1, message: "を選択してください"} 
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  def assign_public_uid
      self.public_uid =  SecureRandom.alphanumeric(5)
  end

end

app/models/venue.rb
class Venue < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '札幌' },
    { id: 3, name: '仙台' },
    { id: 4, name: '東京' },
    { id: 5, name: '横浜' },
    { id: 6, name: '名古屋' },
    { id: 7, name: '京都' },
    { id: 8, name: '大阪' },
    { id: 9, name: '広島' },
    { id: 10, name: '福岡' },
    { id: 11, name: '那覇' }
]
 
  end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_update_path_for(resource)
    root_path
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_reading, :address, :phone_number, :datetime, :blood_type_id, :body_weight, :height, :body_temperature, :allergy_id, :chronic_condition_id, :venue_id, :public_uid])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @registration = Registration.new
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @registration = Registration.new
    flash[:notice]="登録しました"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def index
    @user = User.new
    
  end  

  def show

  end
     
  def create
     @user = User.find_by(id: params[:id])
     @registration = Registration.new(registration_params)
     @registration.save
     redirect_to home_path
  end

  private
  
  def registration_params
    params.require(:registration).permit(:user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:public_uid]   
       user = User.find_by(public_uid: params[:public_uid]) 
       redirect_to user_path(user)
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @registration = Registration.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to  home_path
    else
      render :edit
    end
  end

  def create

  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password__confirmation, :name_reading, :email, :address, :phone_number, :datetime, :blood_type_id, :body_weight, :height, :body_temperature, :allergy_id, :chronic_condition_id, :venue_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>

     <% if current_user.id != 1 %>
      <div class="greeting"> 
        <!-- こんにちは、<%= current_user.name %>さん -->
        こんにちは、
        <%= link_to "#{current_user.name}さん", edit_user_path(current_user), class: :greeting__link%> 
        <br>
        あなたの登録番号：<%= current_user.public_uid %><br> 
        
      </div>
     <% else %>
     <%= notice %>
      <div class="greeting"> 
        <%= notice %><br>
        お疲れ様です、会場登録担当者さん<br><%= notice %>
        現在の接種完了数：<%= Registration.count %>
        <%= notice %>
        <%= form_with url: users_path, method: :get, local: true do |f| %>
          <div class="field">
            <%= f.label :public_uid, "個人番号を入力してください" %><br />
            <%= f.text_field :public_uid, id:"user_public_uid", autofocus: true, autocomplete: "public_uid" %>
            <%= f.hidden_field :id, value: "1" %>
          </div>
        <div class="actions">
          <%= f.submit "登録", class: :form__btn %>
        </div>
        <% end %>
      </div>
     <% end %> 
    <% else %>
      <div class="wrap">
        <div class="item">
         <%= image_tag('pic01.jpg') %>
         <h2>会場担当者ログイン</h2>
         <%= link_to "会場担当者はこちらからログインしてください。",new_user_session_path, class: :main_session %>
        </div>
        <div class="item">
         <%= image_tag('pic02.jpg') %>
         <h2>ユーザー新規登録</h2>
         <%= link_to "初めてワクチン接種をする方は、こちらより登録してください。",new_user_registration_path, class: :main_session %> 
        </div>
        <div class="item">
         <%= image_tag('pic03.jpg') %>
         <h2>マイページログイン</h2>
         <%= link_to "既に登録が済んでいる方は、こちらから個人情報を編集出来ます。",new_user_session_path, class: :main_session %> 
        </div>
      </div>
    <% end %>  

  </div>
</main>

app/views/homes/show.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>

     <% if current_user.id != 1 %>
      <div class="greeting"> 
        <!-- こんにちは、<%= current_user.name %>さん -->
        こんにちは、
        <%= link_to "#{current_user.name}さん", edit_user_path(current_user), class: :greeting__link%> 
        <br>
        あなたの登録番号：<%= current_user.public_uid %><br> 
      </div>
     <% else %>
      <div class="greeting">
        お疲れ様です、会場登録担当者さん<br>
        現在の接種完了数：<%= Registration.count %><br>
        <%= flash[:notice] %><br>
        <%= form_with url: users_path, method: :get, local: true do |f| %>
          <div class="field">
            <%= f.label :public_uid, "個人番号を入力してください" %><br />
            <%= f.text_field :public_uid, id:"user_public_uid", autofocus: true, autocomplete: "public_uid" %>
            <%= f.hidden_field :id, value: "1" %>
          </div>
        <div class="actions">
          <%= f.submit "登録", class: :form__btn %>
        </div>
        <% end %>
      </div>
     <% end %> 
    <% else %>
      <div class="wrap">
        <div class="item">
         <%= image_tag('pic01.jpg') %>
         <h2>会場担当者ログイン</h2>
         <%= link_to "会場担当者はこちらからログインしてください。",new_user_session_path, class: :main_session %>
        </div>
        <div class="item">
         <%= image_tag('pic02.jpg') %>
         <h2>ユーザー新規登録</h2>
         <%= link_to "初めてワクチン接種をする方は、こちらより登録してください。",new_user_registration_path, class: :main_session %> 
        </div>
        <div class="item">
         <%= image_tag('pic03.jpg') %>
         <h2>マイページログイン</h2>
         <%= link_to "既に登録が済んでいる方は、こちらから個人情報を編集出来ます。",new_user_session_path, class: :main_session %> 
        </div>
      </div>
    <% end %>  

  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vaccination_Register</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
            <p>ワクチン登録サイト</P>
            <h5>*このアプリケーションは個人制作物です。関係者、関係省庁と一切関係ありません。</h5>
            <h6>*This application is private.</h6>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ユーザー情報編集</h2>

        <%= form_with model: @user,local: true do |f| %>

        <div class="field">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, id:"user_email", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="field">
          <%= f.label :password, "パスワード（半角英数字混合6文字以上）" %><br />
          <%= f.password_field :password, id:"user_password", autocomplete: "new-password" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "パスワード再入力" %><br />
          <%= f.password_field :password_confirmation, id:"user_password_confirmation", autocomplete: "new-password" %>
        </div>

        <div class="field">
          <%= f.label :name, "名前（全角）" %><br />
          <%= f.text_field :name, id:"user_name" %>
        </div>

        <div class="field">
          <%= f.label :name_reading, "フリガナ（全角）" %><br />
          <%= f.text_field :name_reading, id:"user_name_reading" %>
        </div>

        <div class="field">
          <%= f.label :address, "住所" %><br />
          <%= f.text_area :address, class: :form__text, id:"user_address"%>
        </div>

        <div class="field">
          <%= f.label :phone_number, "電話番号(半角数字ハイフン無し)" %><br />
          <%= f.text_field :phone_number, id:"phone_number" %>
        </div>

        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">生年月日</label>
        </div>
        <div class='input-birth-wrap'>
          <%= raw sprintf(
            f.date_select(
            :datetime,
            class:'select-birth',
            id:"birth-date",
            use_month_numbers: true,
            prompt:'--',
            start_year: 1930,
            end_year: (Time.now.year - 5),
            date_separator: '%s'),
            "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>

        <div class="field">
          <%= f.label :body_weight, "体重(半角)" %><br />
          <%= f.text_field :body_weight, id:"user_body_weight" %>
        </div>

        <div class="field">
          <%= f.label :height, "身長(半角)" %><br />
          <%= f.text_field :height, id:"user_height" %>
        </div>

        <div class="field">
          <%= f.label :body_temperature, "今朝の体温(半角)" %><br />
          <%= f.text_field :body_temperature, id:"user_body_temperature" %>
        </div>

        <div class="items-detail">
          <div class="form">
           <div class="weight-bold-text">
            血液型
           </div>
           <%= f.collection_select(:blood_type_id, BloodType.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
          <div class="weight-bold-text">
            アレルギーの有無
          </div>
           <%= f.collection_select(:allergy_id, Allergy.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
          <div class="weight-bold-text">
            持病の有無
          </div>
           <%= f.collection_select(:chronic_condition_id, ChronicCondition.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
          <div class="weight-bold-text">
            会場
          </div>
           <%= f.collection_select(:venue_id, Venue.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit "編集", class: :form__btn  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= form_with model: [@user,@registration], method: :post, remote: true do |f| %>
<div class="actions">
<%= f.hidden_field :user_id, value: params[:id] %>
登録ボタンを押してください。<br>
<%= f.submit "登録", class: :form__btn %>
</div>
<% end %>